[workspace]
members = [".", "demo"]

[package]
name = "android-view"
version = "0.1.0"
edition = "2024"

[dependencies]
jni = "0.21.1"
ndk = "0.9.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
