[package]
name = "masonry_android"
version = "0.1.0"
edition = "2024"

[dependencies]
accesskit_android = "0.4.0"
android-view = { path = ".." }
masonry_core = { git = "https://github.com/linebender/xilem" }
pollster = "0.4.0"
tracing = "0.1.40"
