[package]
name = "android-view-demo"
version = "0.1.0"
edition = "2024"

[lib]
name = "main"
crate-type = ["cdylib"]

[dependencies]
android-view = { path = ".." }
android_logger = "0.15.0"
log = "0.4.26"
